import type { Metadata } from 'next'
import React from 'react'

import AppProviders from '@/providers/app-provider'

import './globals.css'

//-----------------------------------------------------------------------------------------------

export const metadata: Metadata = {
  title: 'Social Network',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen block relative bg-cushion h-full w-full before:fixed before:inset-0">
        <AppProviders>{children}</AppProviders>
      </body>
    </html>
  )
}
